spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.01:1521/ORCLCDB.localdomain
    username: tuser
    password: tuser
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    context-path: /

    thymeleaf:
      cache: false
      prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
      suffix: .html
      encoding: UTF-8
      mode: HTML5